/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import type { ApiService } from "./ApiService";
import { apiService } from "./ApiService";
export type Services = {
    api: ApiService;
};
export const services = {
    api: apiService
} as const;
