/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupSsoCallbackRouteImport } from './routes/signup.sso-callback'
import { Route as DeviceConnectRouteImport } from './routes/device/connect'
import { Route as DeviceIdRouteImport } from './routes/device/$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupSsoCallbackRoute = SignupSsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => SignupRoute,
} as any)
const DeviceConnectRoute = DeviceConnectRouteImport.update({
  id: '/device/connect',
  path: '/device/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceIdRoute = DeviceIdRouteImport.update({
  id: '/device/$id',
  path: '/device/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signup': typeof SignupRouteWithChildren
  '/device/$id': typeof DeviceIdRoute
  '/device/connect': typeof DeviceConnectRoute
  '/signup/sso-callback': typeof SignupSsoCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signup': typeof SignupRouteWithChildren
  '/device/$id': typeof DeviceIdRoute
  '/device/connect': typeof DeviceConnectRoute
  '/signup/sso-callback': typeof SignupSsoCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/signup': typeof SignupRouteWithChildren
  '/device/$id': typeof DeviceIdRoute
  '/device/connect': typeof DeviceConnectRoute
  '/signup/sso-callback': typeof SignupSsoCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signup'
    | '/device/$id'
    | '/device/connect'
    | '/signup/sso-callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signup'
    | '/device/$id'
    | '/device/connect'
    | '/signup/sso-callback'
  id:
    | '__root__'
    | '/'
    | '/signup'
    | '/device/$id'
    | '/device/connect'
    | '/signup/sso-callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignupRoute: typeof SignupRouteWithChildren
  DeviceIdRoute: typeof DeviceIdRoute
  DeviceConnectRoute: typeof DeviceConnectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/sso-callback': {
      id: '/signup/sso-callback'
      path: '/sso-callback'
      fullPath: '/signup/sso-callback'
      preLoaderRoute: typeof SignupSsoCallbackRouteImport
      parentRoute: typeof SignupRoute
    }
    '/device/connect': {
      id: '/device/connect'
      path: '/device/connect'
      fullPath: '/device/connect'
      preLoaderRoute: typeof DeviceConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device/$id': {
      id: '/device/$id'
      path: '/device/$id'
      fullPath: '/device/$id'
      preLoaderRoute: typeof DeviceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SignupRouteChildren {
  SignupSsoCallbackRoute: typeof SignupSsoCallbackRoute
}

const SignupRouteChildren: SignupRouteChildren = {
  SignupSsoCallbackRoute: SignupSsoCallbackRoute,
}

const SignupRouteWithChildren =
  SignupRoute._addFileChildren(SignupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignupRoute: SignupRouteWithChildren,
  DeviceIdRoute: DeviceIdRoute,
  DeviceConnectRoute: DeviceConnectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
