/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface _Migrations {
  id: Generated<number | null>;
  name: string;
  run_at: Generated<string | null>;
}

export interface Devices {
  created_at: Generated<string | null>;
  id: Generated<number | null>;
  last_seen: string | null;
  light_brightness: number | null;
  light_state: Generated<string | null>;
  name: string;
  online: Generated<number | null>;
  organization_id: number;
  switch_state: Generated<string | null>;
  unique_id: string;
}

export interface Organizations {
  created_at: Generated<string | null>;
  id: Generated<number | null>;
  name: string;
}

export interface Plants {
  created_at: Generated<string | null>;
  device_id: number;
  id: Generated<number | null>;
  location: string;
  plant_type_id: number;
}

export interface PlantTypes {
  created_at: Generated<string | null>;
  description: string | null;
  id: Generated<number | null>;
  name: string;
}

export interface UserOrganizationMemberships {
  created_at: Generated<string | null>;
  id: Generated<number | null>;
  organization_id: number;
  role: string;
  user_id: number;
}

export interface Users {
  created_at: Generated<string | null>;
  email: string;
  id: Generated<number | null>;
  name: string;
  password_hash: string;
  password_salt: string;
}

export interface DB {
  _migrations: _Migrations;
  devices: Devices;
  organizations: Organizations;
  plant_types: PlantTypes;
  plants: Plants;
  user_organization_memberships: UserOrganizationMemberships;
  users: Users;
}
