/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface _Migrations {
  id: Generated<number | null>;
  name: string;
  run_at: Generated<string | null>;
}

export interface AlertNotifications {
  alert_type: string;
  created_at: Generated<number>;
  device_id: number;
  id: Generated<number>;
  last_notified: number | null;
  message: string;
}

export interface Devices {
  created_at: Generated<number>;
  id: Generated<number>;
  lan_ip: string | null;
  lan_ws_port: number | null;
  last_seen: number | null;
  mac_address: string;
  name: string;
  online: Generated<number>;
  user_id: string;
}

export interface DeviceState {
  brightness: Generated<number>;
  device_id: number;
  id: Generated<number>;
  irrigation_on: Generated<number>;
  light_on: Generated<number>;
  temperature: number | null;
  updated_at: Generated<number>;
  water_empty: Generated<number>;
}

export interface IrrigationSchedules {
  active: Generated<number>;
  created_at: Generated<number>;
  device_id: number;
  id: Generated<number>;
  minutes_off: Generated<number>;
  minutes_on: Generated<number>;
  skipped_at: number | null;
  start_at: Generated<number>;
  start_off: Generated<number>;
}

export interface LightSchedules {
  active: Generated<number>;
  created_at: Generated<number>;
  device_id: number;
  id: Generated<number>;
  minutes_off: Generated<number>;
  minutes_on: Generated<number>;
  start_at: Generated<number>;
  start_off: Generated<number>;
}

export interface DB {
  _migrations: _Migrations;
  alert_notifications: AlertNotifications;
  device_state: DeviceState;
  devices: Devices;
  irrigation_schedules: IrrigationSchedules;
  light_schedules: LightSchedules;
}
